### PR TITLE
Don't let normalize recurse into element types

### PR DESCRIPTION
**Pull request by zuiderkwast**
... or "Make normalize head normal form again"

### CODE REVIEW

**Comment by erszcz** [comment]
Hmm, I don't think it's as simple as that. What about
https://github.com/josefs/Gradualizer/blob/0657d76e7de893a2bd7e49e0fac186b732fea434/src/typechecker.erl#L799-L800
https://github.com/josefs/Gradualizer/blob/0657d76e7de893a2bd7e49e0fac186b732fea434/src/typechecker.erl#L802
https://github.com/josefs/Gradualizer/blob/0657d76e7de893a2bd7e49e0fac186b732fea434/src/typechecker.erl#L805 to name a few? I think all of these will lead to broken test cases, though I haven't checked.

**Comment by zuiderkwast** [comment]
You're right, I've lost it. :sob: I'll have to study this source code from scratch.

Anyway, Head Normal Form is about not recursing fully down the tree. I'm pretty sure it was like that once upon a time, but I don't know since when and why it's not the case anymore.

**Comment by erszcz** [comment]
> https://github.com/josefs/Gradualizer/blob/0657d76e7de893a2bd7e49e0fac186b732fea434/src/typechecker.erl#L802 
> 
> https://github.com/josefs/Gradualizer/blob/0657d76e7de893a2bd7e49e0fac186b732fea434/src/typechecker.erl#L805

Apparently, the above can be removed with no tests breaking. It's not that nice with this one, though:

> https://github.com/josefs/Gradualizer/blob/0657d76e7de893a2bd7e49e0fac186b732fea434/src/typechecker.erl#L799-L800

Quite a lot started failing when I tried that :/

**Comment by erszcz** [comment]
I think this can be closed now, WDYT @zuiderkwast?

**Pull request closed without merging**
