### PR TITLE
Use ExDoc

### PR DESCRIPTION
**Pull request by erszcz**
Screenshot 2022-09-14 at 22 04 22
Screenshot 2022-09-14 at 22 04 16

The docs aren't hosted online anywhere, but it would be quite easy to host them on GH Pages or https://hexdocs.pm.

### CODE REVIEW

**Comment by zuiderkwast** [comment]
Feel free to upload it to hexdocs if you want. Do you want to publish gradualizer on hex as well?

**Comment by erszcz** [comment]
> I didn't know you can use ExDoc for plain Erlang projects.

Yeah, it was a journey, but it's possible for some time now, thanks to our work in the EEF Docs and then Build and Packaging working groups. I borrowed some doc handling/storage ideas from Elixir for [docsh](https://github.com/erszcz/docsh), then based on that we (Jose Valim, I, and Eric Bailey) sketched EEP-48, Lukas Larsson added doc chunk support and shell_docs to OTP 23.0, I added doc chunk support to EDoc for OTP 24.0, Jose and Wojtek Mach did their part in ExDoc to handle both languages, and Bryan Paxton packaged that as `rebar3_ex_doc`. That's how we got it :)

> Feel free to upload it to hexdocs if you want. Do you want to publish gradualizer on hex as well?

I think there's already a package available on Hex, but a bit outdated with regard to the current master. There have been no versions tagged for a while. No docs on hexdocs, though. I think I can upload these at some point in the next few days, but I might need the permissions for the existing package on Hex - @zuiderkwast could you add me (https://hex.pm/users/erszcz) there?

**Comment by zuiderkwast** [comment]
:+1: I added you as an owner of the Hex package now.

**Comment by erszcz** [comment]
Any comments on this one? I'm thinking of tagging a release after merging it - there hasn't been one for a looong time. WDYT?

**Comment by zuiderkwast** [comment]
Sounds good.

I see there are some other stuff in this PR such as README changes.

@josefs please check if you agree with the changes to README.md

**Review by josefs — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
